### PR TITLE
Remove sync command

### PR DESCRIPTION
**Pull request by daavoo**
It doesn't exist.

### CODE REVIEW

**Comment by jonburdo** [comment]
@volkfox Should we go ahead and add this command? I don't think we had an issue for it

**Comment by volkfox** [comment]
> @volkfox Should we go ahead and add this command? I don't think we had an issue for it

I think we should add it at some point.

SYNC is a way to cope with object deletions that were done in the workspace, e.g. some noisy images that can be killed on the spot.

**Comment by daavoo** [comment]
I like the idea of the command (I discovered it didn't exist because it was exactly what I needed).

As a workaround, I handled deletions in the workspace via annotation updates to be later filtered via query and it didn't feel that bad.

**Comment by volkfox** [comment]
ok lets fix it by implementing to the doc

**Comment by daavoo** [comment]
Closing in favor of https://github.com/iterative/ldb/issues/215

**Pull request closed without merging**
